version: "3"

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "59999:80"
    volumes:
      - ./data/static:/usr/share/nginx/html
      - ./data/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/mime.types:/etc/nginx/mime.types:ro
      - ./data/logs/:/logs
    networks:
      - aigou-network
  db-mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data/db/mysql:/var/lib/mysql
      - ./data/sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    networks:
      - aigou-network
  app:
    build: .
    restart: always
    depends_on:
      - db-mysql
      - nginx
    volumes:
      - ~/.m2:/root/.m2
    environment:
      DB_USERNAME: root
      DB_PASSWORD: my-secret-pw
      DB_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      DB_URL: jdbc:mysql://db-mysql/aigou?serverTimezone=UTC
    networks:
      - aigou-network

networks:
  aigou-network:
