server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql:///aigou?serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
